// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 3/11/2026, 6:22:17 PM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.ts";
const config = [
{"content":{"files":["/Users/hastichavda/projects/web/News-Website-main/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/hastichavda/projects/web/News-Website-main/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/hastichavda/projects/web/News-Website-main/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/hastichavda/projects/web/News-Website-main/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/hastichavda/projects/web/News-Website-main/plugins/**/*.{js,ts,mjs}","/Users/hastichavda/projects/web/News-Website-main/composables/**/*.{js,ts,mjs}","/Users/hastichavda/projects/web/News-Website-main/utils/**/*.{js,ts,mjs}","/Users/hastichavda/projects/web/News-Website-main/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/hastichavda/projects/web/News-Website-main/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/hastichavda/projects/web/News-Website-main/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/hastichavda/projects/web/News-Website-main/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;